In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("life_expectancy_data.csv")

In [3]:
df.head()

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Afghanistan,2015,Developing,65.0,263.0,62,0.01,71.279624,65.0,1154,...,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,2014,Developing,59.9,271.0,64,0.01,73.523582,62.0,492,...,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,Afghanistan,2013,Developing,59.9,268.0,66,0.01,73.219243,64.0,430,...,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,Afghanistan,2012,Developing,59.5,272.0,69,0.01,78.184215,67.0,2787,...,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,Afghanistan,2011,Developing,59.2,275.0,71,0.01,7.097109,68.0,3013,...,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5

In [5]:
df.tail()

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
2933,Zimbabwe,2004,Developing,44.3,723.0,27,4.36,0.0,68.0,31,...,67.0,7.13,65.0,33.6,454.366654,12777511.0,9.4,9.4,0.407,9.2
2934,Zimbabwe,2003,Developing,44.5,715.0,26,4.06,0.0,7.0,998,...,7.0,6.52,68.0,36.7,453.351155,12633897.0,9.8,9.9,0.418,9.5
2935,Zimbabwe,2002,Developing,44.8,73.0,25,4.43,0.0,73.0,304,...,73.0,6.53,71.0,39.8,57.348340,125525.0,1.2,1.3,0.427,10.0
2936,Zimbabwe,2001,Developing,45.3,686.0,25,1.72,0.0,76.0,529,...,76.0,6.16,75.0,42.1,548.587312,12366165.0,1.6,1.7,0.427,9.8
2937,Zimbabwe,2000,Developing,46.0,665.0,24,1.68,0.0,79.0,1483,...,78.0,7.10,78.0,43.5,547.358878,12222251.0,11.0,11.2,0.434,9.8

In [7]:
df_sweden = df[df['Country'] == 'Sweden']
df_sweden.head()

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
2505,Sweden,2015,Developed,82.4,53.0,0,NaN,0.000000,67.0,22,...,98.0,NaN,98.0,0.1,5585.25847,9799186.0,1.5,1.4,0.909,15.9
2506,Sweden,2014,Developed,82.3,54.0,0,7.3,1142.212403,67.0,26,...,98.0,11.93,98.0,0.1,5918.19898,969611.0,1.5,1.3,0.906,15.8
2507,Sweden,2013,Developed,81.9,57.0,0,7.3,1212.666327,67.0,51,...,98.0,11.97,98.0,0.1,6283.24522,96379.0,1.4,1.3,0.904,15.8
2508,Sweden,2012,Developed,81.7,57.0,0,7.4,10947.023270,53.0,30,...,98.0,11.80,98.0,0.1,57134.77700,9519374.0,1.4,1.3,0.903,15.8
2509,Sweden,2011,Developed,81.7,58.0,0,7.4,11477.667100,42.0,26,...,98.0,11.70,98.0,0.1,59593.28711,9449213.0,1.4,1.3,0.901,16.0

In [11]:
df_italy = df[df['Country'] == 'Italy']
df_italy.head(20)

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
1282,Italy,2015,Developed,82.7,56.0,1,NaN,0.000000,93.0,159,...,93.0,NaN,93.0,0.1,349.14755,673582.0,0.6,0.6,0.881,16.3
1283,Italy,2014,Developed,82.5,57.0,2,7.56,4831.644796,95.0,0,...,95.0,9.25,95.0,0.1,35396.66517,678914.0,0.6,0.6,0.877,16.3
1284,Italy,2013,Developed,82.3,58.0,2,7.35,483.191684,96.0,0,...,96.0,9.22,96.0,0.1,3537.27441,6233948.0,0.5,0.6,0.876,16.5
1285,Italy,2012,Developed,82.0,6.0,2,7.49,4793.904924,96.0,376,...,96.0,9.28,97.0,0.1,34814.12436,59539717.0,0.5,0.6,0.877,16.6
1286,Italy,2011,Developed,82.0,6.0,2,6.98,5439.691769,96.0,5189,...,96.0,9.27,96.0,0.1,38334.68477,59379449.0,0.5,0.5,0.872,16.4
1287,Italy,2010,Developed,81.8,6.0,2,6.95,5219.668802,96.0,372,...,96.0,9.42,96.0,0.1,35849.37364,59277417.0,0.5,0.5,0.869,16.4
1288,Italy,2009,Developed,81.6,61.0,2,7.25,5243.316638,96.0,351,...,96.0,9.41,96.0,0.1,36976.84512,5995365.0,0.5,0.5,0.868,16.3
1289,Italy,2008,Developed,81.5,61.0,2,7.96,66.378405,96.0,1617,...,96.0,8.89,96.0,0.1,464.18465,58826731.0,0.5,0.5,0.866,16.3
1290,Italy,2007,Developed,81.3,63.0,2,8.37,5228.821581,97.0,321,...,97.0,8.48,97.0,0.1,37698.78573,5843831.0,0.5,0.5,0.862,16.1
1291,Italy,2006,Developed,81.2,65.0,2,8.44,473.191545,96.0,439,...,97.0,8.82,96.0,0.1,3341.74820,58143979.0,0.5,0.5,0.856,16.0
1292,Italy,2005,Developed,88.0,66.0,2,8.65,4506.255963,96.0,135,...,97.0,8.71,95.0,0.1,31959.26215,57969484.0,0.5,0.5,0.851,15.8
1293,Italy,2004,Developed,89.0,66.0,2,8.98,4270.914882,96.0,599,...,97.0,8.49,94.0,0.1,31174.56118,57685327.0,0.5,0.5,0.846,15.6
1294,Italy,2003,Developed,79.9,72.0,2,9.30,3519.258515,95.0,10982,...,97.0,8.17,96.0,0.1,27387.22580,5731323.0,0.5,0.5,0.841,15.4
1295,Italy,2002,Developed,80.0,72.0,2,9.25,2883.334911,95.0,9385,...,96.0,8.23,93.0,0.1,22196.57360,57597.0,0.5,0.5,0.836,15.2
1296,Italy,2001,Developed,79.8,75.0,2,9.69,3.122230,95.0,0,...,96.0,8.11,93.0,0.1,24.81900,569741.0,0.5,0.5,0.828,14.9
1297,Italy,2000,Developed,79.4,77.0,3,9.78,31.505822,94.0,1457,...,97.0,7.91,87.0,0.1,251.24260,5694218.0,0.5,0.5,0.823,14.8

In [10]:
df_japan = df[df['Country'] == 'Japan']
df_japan.head()

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
1314,Japan,2015,Developed,83.7,55.0,2,NaN,0.000000,NaN,35,...,99.0,NaN,96.0,0.1,34474.13736,127141.0,2.1,1.8,0.902,15.3
1315,Japan,2014,Developed,83.5,57.0,2,0.01,88.833622,NaN,462,...,99.0,1.23,96.0,0.1,3896.21151,127276.0,2.0,1.7,0.899,15.3
1316,Japan,2013,Developed,83.5,56.0,2,7.55,94.434286,NaN,229,...,99.0,1.25,96.0,0.1,4454.44746,127445.0,2.0,1.7,0.894,15.3
1317,Japan,2012,Developed,83.3,58.0,2,7.39,121.586916,NaN,228,...,99.0,1.17,97.0,0.1,4863.47665,127629.0,1.9,1.7,0.889,15.3
1318,Japan,2011,Developed,82.5,64.0,3,7.39,9498.729062,NaN,434,...,96.0,1.70,97.0,0.1,48167.99727,127833.0,1.9,1.6,0.884,15.1

In [4]:
df.describe()

,Year,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,BMI,under-five deaths,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
count,2938.000000,2928.000000,2928.000000,2938.000000,2744.000000,2938.000000,2385.000000,2938.000000,2904.000000,2938.000000,2919.000000,2712.00000,2919.000000,2938.000000,2490.000000,2.286000e+03,2904.000000,2904.000000,2771.000000,2775.000000
mean,2007.518720,69.224932,164.796448,30.303948,4.602861,738.251295,80.940461,2419.592240,38.321247,42.035739,82.550188,5.93819,82.324084,1.742103,7483.158469,1.275338e+07,4.839704,4.870317,0.627551,11.992793
std,4.613841,9.523867,124.292079,117.926501,4.052413,1987.914858,25.070016,11467.272489,20.044034,160.445548,23.428046,2.49832,23.716912,5.077785,14270.169342,6.101210e+07,4.420195,4.508882,0.210904,3.358920
min,2000.000000,36.300000,1.000000,0.000000,0.010000,0.000000,1.000000,0.000000,1.000000,0.000000,3.000000,0.37000,2.000000,0.100000,1.681350,3.400000e+01,0.100000,0.100000,0.000000,0.000000
25%,2004.000000,63.100000,74.000000,0.000000,0.877500,4.685343,77.000000,0.000000,19.300000,0.000000,78.000000,4.26000,78.000000,0.100000,463.935626,1.957932e+05,1.600000,1.500000,0.493000,10.100000
50%,2008.000000,72.100000,144.000000,3.000000,3.755000,64.912906,92.000000,17.000000,43.500000,4.000000,93.000000,5.75500,93.000000,0.100000,1766.947595,1.386542e+06,3.300000,3.300000,0.677000,12.300000
75%,2012.000000,75.700000,228.000000,22.000000,7.702500,441.534144,97.000000,360.250000,56.200000,28.000000,97.000000,7.49250,97.000000,0.800000,5910.806335,7.420359e+06,7.200000,7.200000,0.779000,14.300000
max,2015.000000,89.000000,723.000000,1800.000000,17.870000,19479.911610,99.000000,212183.000000,87.300000,2500.000000,99.000000,17.60000,99.000000,50.600000,119172.741800,1.293859e+09,27.700000,28.600000,0.948000,20.700000